#!/bin/python3
from sys import argv, stderr
from error_case import *


def print_usage():
    print("USAGE:")
    print("    ./106bombyx n [k | i0 i1]\n")
    print("DESCRIPTION")
    print("    n      number of first generation individuals")
    print("    k      growth rate from 1 to 4")
    print("    i0     initial generation (included)")
    print("    i1     final generation (included)")
    return 0


def n_to_k(n, k):
    for i in range(1, 101):
        if n < 0:
            n = 0
        print(i, "{:.2f}".format(n))
        n = k * n * (1000 - n) / 1000
    return 0


def n_to_i(n, i0, i1):
    k = 1.00
    while k <= 4.00:
        j = 1
        n = int(argv[1])
        while j < i0:
            if n < 0:
                n = 0
            n = k * n * (1000 - n) / 1000
            j += 1
        while j <= i1:
            if n < 0:
                n = 0
            print("{:.2f} {:.2f}".format(k, n))
            n = k * n * (1000 - n) / 1000
            j += 1
        k += 0.01
    return 0


if __name__ == "__main__":
    if len(argv) == 2 and argv[1] == "-h":
        print_usage()
    elif len(argv) == 3:
        n, k = check_two_args()
        n_to_k(n, k)
    elif len(argv) == 4:
        n, i0, i1 = check_three_args()
        n_to_i(n, i0, i1)
    else:
        print("Bad arguments", file=stderr)
        exit(84)
    exit(0)
